version: "3"
services:
  web:
    build:
      context: docker/
    volumes:
      - .:/usr/local/team_monitor/
    ports:
      - 8000:8000
    privileged: true
    entrypoint:
      - /usr/local/team_monitor/entrypoint.sh
