version: "3"
services:
  web:
    build:
      context: docker/
    volumes:
      - .:/usr/local/team_monitor/
    privileged: true
    entrypoint:
      - /usr/local/team_monitor/scripts/run_test.sh
