# Generated by Django 3.1.7 on 2021-02-26 07:00
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0003_team_avg_mood")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="total_average",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team", name="total_better", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="team",
            name="total_excellent",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="team", name="total_good", field=models.IntegerField(default=0)
        ),
        migrations.AddField(
            model_name="team", name="total_sad", field=models.IntegerField(default=0)
        ),
        migrations.AlterField(
            model_name="team", name="avg_mood", field=models.IntegerField(default=0)
        ),
    ]
