# Generated by Django 3.1.7 on 2021-02-27 04:09
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("api", "0005_auto_20210226_0707")]

    operations = [
        migrations.RemoveField(model_name="team", name="avg_mood"),
        migrations.RemoveField(model_name="team", name="total_average"),
        migrations.RemoveField(model_name="team", name="total_better"),
        migrations.RemoveField(model_name="team", name="total_excellent"),
        migrations.RemoveField(model_name="team", name="total_good"),
        migrations.RemoveField(model_name="team", name="total_sad"),
        migrations.CreateModel(
            name="TeamStatistic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avg_mood",
                    models.IntegerField(
                        choices=[
                            (1, "Sad"),
                            (2, "Normal"),
                            (3, "Good"),
                            (4, "Better"),
                            (5, "Excellent"),
                        ],
                        default=1,
                    ),
                ),
                ("total_sad", models.IntegerField(default=0)),
                ("total_average", models.IntegerField(default=0)),
                ("total_good", models.IntegerField(default=0)),
                ("total_better", models.IntegerField(default=0)),
                ("total_excellent", models.IntegerField(default=0)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.team"
                    ),
                ),
            ],
        ),
    ]
