# Generated by Django 3.1.7 on 2021-02-27 14:07
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0007_remove_employee_current_mood_level")]

    operations = [
        migrations.RenameField(
            model_name="teamstatistic",
            old_name="total_average",
            new_name="total_normal",
        )
    ]
