# Generated by Django 3.1.7 on 2021-02-28 18:21
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("api", "0008_auto_20210227_1407")]

    operations = [
        migrations.RenameField(
            model_name="moodlevel", old_name="mood_level", new_name="level"
        )
    ]
